name: "Build and push server"

on:
  push:
    branches:
      - main
    paths:
      - apps/reader/**
      - apps/server/**


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # allow issuing OIDC tokens for this workflow run
      id-token: write
      # allow at least reading the repo contents, add other permissions if necessary
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - uses: depot/setup-action@v1
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: depot/build-push-action@v1
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
        with:
          project: jrks6t6pbc
          push: true
          tags: aeolun/writer-server:latest
          context: ./
          file: apps/server/Dockerfile
      - name: Build reader app
        run: pnpm run --filter=@writer/reader build
      - name: Build and push reader
        uses: depot/build-push-action@v1
        env:
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}
        with:
          project: jrks6t6pbc
          push: true
          tags: aeolun/writer-reader:latest
          context: ./apps/reader
          file: apps/reader/Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        # webhook call to portainer to deploy the new stack
        run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}